version = 0.1

[staging.deploy.parameters]
stack_name = "PLANNER-STAGING"
resolve_s3 = true
s3_prefix = "PLANNER-STAGING"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = "StageName=Stage"

[production.deploy.parameters]
stack_name = "PLANNER-PROD"
resolve_s3 = true
s3_prefix = "PLANNER-PROD"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
parameter_overrides = "StageName=Prod"

[default.global.parameters]
region = "ap-southeast-2"
